apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-of-object-detection-2-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/test-of-object-detection-2/overlays/development
    repoURL: https://github.com/gabemontero-appstudio-test-org/test-detr-2-gitops.git
    targetRevision: main
  destination:
    namespace: rhdh-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: ai-rhdh
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
